### ISSUE TITLE
Question about account seeds

### ISSUE THREAD

**Issue by labyla** [Allen-Taylor/moonshot_py#1]
Hello! I can't understand how you find seeds for accounts (for example seeds for curve account: "token" & mint address). Could you please explain it to me? I would be very grateful.

**Comment by AL-THE-BOT-FATHER** [comment]
It ensures the curve address is unique but deterministic. The combo of the seed, mint and program id will always produce that same address. 

The seed is determined by the creator of the program, not me. I simplify found it in the nodejs SDK.

For example, moonshot uses "token" as the seed, pump fun used "bonding-curve" as the seed. The seed can be whatever the creator wants though, it just needs to be consistent.

Hope that makes sense.
