### ISSUE TITLE
Double signature

### ISSUE THREAD

**Issue by Metalingus** [Allen-Taylor/moonshot_py#1]
I guess no way of sending a transaction without the backendAuthority keypair?

**Comment by Allen-Taylor** [comment]
I'm not exactly sure how it works, but I'm guessing you send a partially signed transaction to an endpoint, then they add the second signature. Still trying to figure it out.

**Comment by Metalingus** [comment]
So far all I've found is that indeed we need the backendAuthority as a signer otherwise the transaction fails

**Comment by Metalingus** [comment]
I am getting this error:
 #1 - Token_launchpad: Buy (Program Error: "The given account did not sign")
 I guess it refers to the backend keypair, I hope they remove this restriction or someone finds a workaround

**Comment by Allen-Taylor** [comment]
I plan on doing some network captures to see what if going on in the background when you swap on Moonswap. Like I was saying, I believe there has to be some kind of API endpoint where you submit a partially signed transaction, then they sign on the backend. It is very highly unlikely the PK resides in the client side code. 

I'll be sharing all of my findings on this repo. Thanks for the interest.

**Comment by Metalingus** [comment]
Cool looking forward to that, I did a quick network monitoring and indeed there's an API call that returns a serialized transaction however upon deserializing it, I found two blank signatures, one linked to my pubkey and another one linked to the backend. Maybe you'll be able to get the right sigs.

**Comment by Allen-Taylor** [comment]
Do you have TG? Can you ping me on there. 

Telegram: Allen_A_Taylor (AL THE BOT FATHER)

**Comment by Allen-Taylor** [comment]
can you share some images of the captures? or the end points and their parameters?

**Comment by zwq652997** [comment]
It seems that we have to rely on the dexscreener API?

**Comment by Allen-Taylor** [comment]
> It seems that we have to rely on the Dexscreener API?

Seems so. Transactions will fail without the second signer (tested by Metalingus).

It kind of works like Jupiter V6 API where it creates the transaction for you, you just sign and send. However, in this case it gives you a partially signed transaction.
